### ISSUE TITLE
Payload type in getLaunchNotification vs. push-notification callback

### ISSUE THREAD

**Issue by zarko-tg** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#100]
Hey @shaders,

In
```javascript
document.addEventListener( 'push-notification', function ( event ) {
  ...
});
```
the payload represented in event.notification is of type object, while the payload returned in the callback of getLaunchNotification (when not null) is of type string.

For the sake of consistency getLaunchNotification should be changed to return a payload as an object.

**Comment by shaders** [comment]
done

**Comment by zarko-tg** [comment]
For anyone that might be looking at issues with getLaunchNotification - Pushwoosh seems to have decided to go back to returning a string. We weren't aware of this until now, basically almost 4 years later.
