### ISSUE TITLE
Impossible to reproduce custom sound on iOs

### ISSUE THREAD

**Issue by xale76** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#101]
I'm using Intel XDK Cordova app ( I think It's very close to phonegap).

I'm trying to use a custom sound (duck.caf, generated from a wav file as Os says). I tried anything but when a new push arrives on my iOs device the default sound is played (on my Android device the sound is the custom one -duck.wav-, and it's right).
I placed my duck.caf into different folders (main folder, JS folder, index.html folder and so on). Is it possible to know where the iOs app founds the file? please help me

**Comment by shaders** [comment]
The sounds have to go to the main app folder. (caf format is ok). Make sure it is in the main folder where Info.plist is located. It is requirement of iOS. To double check - you can unzip ipa file and check .app contents.

**Comment by xale76** [comment]
This is my problem. Intel XDK puts files in main root into "www" folder,
where index.html is placed. So the .caf file is into www.
So what's the solution?

[image: Immagine in linea 1]

2015-06-08 18:19 GMT+02:00 shaders <notifications@github.com>:

**Comment by xale76** [comment]
anyway I solved my problem! thank You!
You gave me the perfect tip!


2015-06-08 19:23 GMT+02:00 Alessandro Sbenaglia <xale76@gmail.com>:
