### ISSUE TITLE
Notification on tray even when app is in foreground

### ISSUE THREAD

**Issue by alejandromagnorsky** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#103]
I wanted to ask for a new feature if possible. Refer to this link please:
https://community.pushwoosh.com/questions/2287/notification-on-tray-even-when-app-is-in-foreground

**Comment by shaders** [comment]
Hi,

It's supported in the latest published release.

Use the following metadata key in AndroidManifest.xml (http://developer.android.com/guide/topics/manifest/meta-data-element.html): 

&lt;meta-data android:name="PW_NO_BROADCAST_PUSH" android:value="true" /&gt;
