### ISSUE TITLE
Location Permission Clarification

### ISSUE THREAD

**Issue by arulapj** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#104]
Hi,
Can you list permission requested by this plugin, when included it was asking for GPS precise location as well as network location.. this panics our users from using our app

please clarify

thank you

**Comment by shaders** [comment]
This is the list of permissions used by the plugin. Make sure you are using the latest version of the plugin or maybe some other plugin enabled GPS precise location.

        <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

        <uses-permission android:name="android.permission.VIBRATE" />

        
        <uses-permission android:name="android.permission.INTERNET"/>

        
        <uses-permission android:name="android.permission.WAKE_LOCK"/>

        
        <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

**Comment by shaders** [comment]
more details here: https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/blob/master/plugin.xml

look for uses-permission

**Comment by arulapj** [comment]
Hi,

i can see a service <service android:name="com.arellomobile.android.push.GeoLocationService"/> using geo location.. is this casuing the GPS

**Comment by shaders** [comment]
No, as long as you don't declare permission AND call startLocationTracking method.
