### ISSUE TITLE
iOS badge issue

### ISSUE THREAD

**Issue by saurabhgupta050890** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#106]
I have implemented this plugin in both Android and iOS and it works great. But there are a few things that I noticed:

1. If app is in background or closed and a push notification is received, if user opens app directly then notification is not removed from tray until removed manually or tapped upon.

2.  If a badge is send in the push notification then it will only be cleared from app icon if notification is tapped. If user clears notification or starts app from icon then it doesn't removed.

**Comment by shaders** [comment]
1. Yes, this is by design. Call "clearNotificationCenter" function to clear the pushes.

2. This is by design. Call "setApplicationIconBadgeNumber" function to clear badge icon.
