### ISSUE TITLE
Failed to regiester : "Missing Command Error" on windows platform (windows universal app)

### ISSUE THREAD

**Issue by vwong53** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#107]
Hi, i'm a newbie here. I'm creating a windows universal app (windows 8.1) using cordova which Microsoft is pushing at this direction. After adding pushwoosh-phonegap plugin and exec the code, i kept getting this error 'Failed to regiester : "Missing Command Error"'. When i check in the "src" folder, it only has "android", 'ios" and "wp8".

So any solution to fix this problem??

**Comment by shaders** [comment]
Do you use Phonegap Build or compile locally?

**Comment by vwong53** [comment]
I compile using visual studio community.

**Comment by shaders** [comment]
Currently Pushwoosh supports Windows Phone for Phonegap/Cordova. Support for Windows 8.1 will be added in the nearest future.

**Comment by edegut** [comment]
It seems that pushwoosh now support Win8.1, but I have the same error "Missing Command Error", any idea why?

**Comment by menezes91** [comment]
I'm having the same problem on a clean project.
If i make:
cordova create example
cordova platform add wp8
cordova plugin add pushwoosh-cordova-plugin
cordova plugin add cordova-plugin-whitelist
Then i add the script to index.js
Add <access origin="*.pushwoosh.com" /> to config.xml
Run and then "["failed to register ","Missing Command Error"]"

**Comment by edegut** [comment]
any news?

**Comment by DimanAM** [comment]
Pushwoosh did not support Windows platform until 4.0.0 release
