### ISSUE TITLE
Cannot call method 'trim' of null error when included in AppGyver Build Service

### ISSUE THREAD

**Issue by griffinfujioka** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#109]
I've followed the following guide to configure the PushWoosh PhoneGap 3.0 plugin into my Steroids application: http://docs.appgyver.com/tooling/build-service/plugins/configuring-custom-plugins/

I have forked the plugin and tried a handful of modifications to the plugin.xml file here: https://github.com/griffinfujioka/pushwoosh-phonegap-3.0-plugin

However I am still seeing the following error: Adding plugin from: https://github.com/griffinfujioka/pushwoosh-phonegap-3.0-plugin
Cannot call method 'trim' of null

I have looked through a number of forums for help with this issue and none of the suggested workarounds solve the issue. Here are some forums I've looked at:
* http://community.appgyver.com/t/error-when-building-with-pushwoosh-plugin/4909
* https://github.com/AppGyver/steroids/issues/888

Can anyone provide any insight into what's going on? It seems like an issue with Plugman to me.

**Comment by shaders** [comment]
Have you tried contacting AppsGyver support? It you have pull request of what to change in config.xml I would merge that. So far it works perfectly with plugman on Phonegap Build Service... I wish I knew what to fix.

**Comment by griffinfujioka** [comment]
We contacted AppGyver support this morning and are waiting to hear back. I will update this thread if we figure something out.

**Comment by harsaharsa** [comment]
AppGyver employee here! I found the problem. It's because our wrapper has a different base `AndroidManifest.xml` file that doesn't include the `/manifest/application/activity` element path by default. Thus, plugman fails when it tries to iterate through the element at https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/blob/master/plugin.xml#L60-L65

If you move that whole block to after the next element, i.e. to line 107, it seems to compile fine (didn't test that it works though). Note that you still need to account for https://github.com/AppGyver/steroids/issues/992

Sorry for the confusion, it would've been pretty impossible to debug on your own! :(

**Comment by g-liu** [comment]
Thank you for fixing your side of AppGyver! We have also made the necessary changes and got a build success... about 30 builds later :sweat_smile:

**Comment by griffinfujioka** [comment]
Thanks for your help. 

We are able to successfully compile our AppGyver application with the PushWoosh plugin included. However, our iOS build still fails when the PushWoosh plugin is included. 

It seems like a compiler issue wherein the CDVViewController class is not recognized. 

Could this be a related issue? 

Thanks again.

```
/Users/administrator/app-builder/STAGING/client/Plugins/com.pushwoosh.plugins.pushwoosh/ios/PushNotification.m:81:35: error: receiver type 'CDVViewController' for instance message is a forward declaration
        PushNotification *pushHandler = [delegate.viewController getCommandInstance:@"PushNotification"];
                                         ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/administrator/app-builder/STAGING/client/Plugins/com.pushwoosh.plugins.pushwoosh/ios/PushNotification.m:15:
/Users/administrator/app-builder/STAGING/client/AppGyver/Views and Controllers/AppDelegate/AppDelegate.h:13:8: note: forward declaration of class here
@class CDVViewController;
       ^
/Users/administrator/app-builder/STAGING/client/Plugins/com.pushwoosh.plugins.pushwoosh/ios/PushNotification.m:238:36: error: receiver type 'CDVViewController' for instance message is a forward declaration
                PushNotification *pushHandler = [delegate.viewController getCommandInstance:@"PushNotification"];
                                                 ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/administrator/app-builder/STAGING/client/Plugins/com.pushwoosh.plugins.pushwoosh/ios/PushNotification.m:15:
/Users/administrator/app-builder/STAGING/client/AppGyver/Views and Controllers/AppDelegate/AppDelegate.h:13:8: note: forward declaration of class here
@class CDVViewController;
       ^
/Users/administrator/app-builder/STAGING/client/Plugins/com.pushwoosh.plugins.pushwoosh/ios/PushNotification.m:361:35: error: receiver type 'CDVViewController' for instance message is a forward declaration
        PushNotification *pushHandler = [delegate.viewController getCommandInstance:@"PushNotification"];
                                         ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/administrator/app-builder/STAGING/client/Plugins/com.pushwoosh.plugins.pushwoosh/ios/PushNotification.m:15:
/Users/administrator/app-builder/STAGING/client/AppGyver/Views and Controllers/AppDelegate/AppDelegate.h:13:8: note: forward declaration of class here
@class CDVViewController;
       ^
3 errors generated.

** BUILD FAILED **


The following build commands failed:
	CompileC build/Debug-iphoneos/Build/Intermediates/AppGyver.build/Debug-iphoneos/Scanner\ RC.build/Objects-normal/armv7/PushNotification.o Plugins/com.pushwoosh.plugins.pushwoosh/ios/PushNotification.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by shaders** [comment]
Actually it is safe to remove:
https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/blob/master/plugin.xml#L60-L65
from plugin.xml as Pushwoosh Android SDK does not need these lines anymore.
(Will remove them in the update).

As for iOS:
Plugin assumes default Phonegap AppDelegate structure with:
@property (nonatomic, strong) IBOutlet CDVViewController* viewController;

As it needs CDVViewController to get plugin instance from UIApplication category in order to set up Native iOS push notifications callbacks:
```
@implementation UIApplication(InternalPushRuntime)

- (NSObject<PushNotificationDelegate> *)getPushwooshDelegate {
	AppDelegate *delegate = [[UIApplication sharedApplication] delegate];
	PushNotification *pushHandler = [delegate.viewController getCommandInstance:@"PushNotification"];
	return pushHandler;
}
@end
```

Knowing the AppGyver AppDelegate would help to solve this.

**Comment by harsaharsa** [comment]
Checked this with our dev, the code is fundamentally incompatible. PhoneGap exposes the CDVViewController through the shared application instance, but we have multiple WebViews and thus multiple CDVViewControllers.

However, CDVPlugin does have an accessor for the CDVViewController via the `viewController` property:

```objective-c
// CDVPlugin.h

@property (nonatomic, weak) UIViewController* viewController; // instance of CDVViewController
```

So you might be able to rewrite the code to use that one, no guarantees that it'll work though. You should also make sure you're only initializing the plugin in a single WebView to avoid conflicts of multiple plugin instances running at the same time.

**Comment by enricodeleo** [comment]
Same issue here, it could be very useful to have a compatible version of Pushwoosh since I'm going to drop the service for this reason and it's a pity 'cause Ilike it very much :(

**Comment by shaders** [comment]
Let me think of other ways to handle that. I'll keep you posted.

**Comment by g-liu** [comment]
We were able to make this plugin work with iOS by adding the following line to `PushNotification.h`:

    #import <Cordova/CDV.h>

This is actually taken from https://github.com/VillageLuxe/pushwoosh-phonegap-3.0-plugin who resolved the issue in the same way. See https://github.com/g-liu/pushwoosh-phonegap-3.0-plugin/commit/0a31ce78376fd5d4a3e00233d15ab1a238b0559f.
