### ISSUE TITLE
Cannot build any longer after update of 2 hours ago

### ISSUE THREAD

**Issue by xale76** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#110]
HELP! before your update everything works well.
I use Intel XDK cordova, now when I compile I got this error

-compile:
    [javac] Compiling 17 source files to .../LocalMed_Prof/bin/classes
    [javac] .../LocalMed_Prof/src/com/pushwoosh/plugin/pushnotifications/PushNotifications.java:718: error: cannot find symbol
    [javac] 				PushManager.sendGoalAchieved(cordova.getActivity(), goal, count);
    [javac] 				           ^
    [javac]   symbol:   method sendGoalAchieved(Activity,String,Integer)
    [javac]   location: class PushManager
    [javac] Note: .../LocalMed_Prof/src/com/intel/xdk/device/Device.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: .../LocalMed_Prof/src/com/intel/xdk/device/Device.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

Please help me!!!!

**Comment by shaders** [comment]
Fixed
