### ISSUE TITLE
Priority for Android devices

### ISSUE THREAD

**Issue by antonvovchenko** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#113]
Hi all!

Does this plugin support android_priority parameter mentioned here - https://www.pushwoosh.com/programming-push-notification/pushwoosh-push-notification-remote-api/#PushserviceAPI-Method-messages-create ?

Or in other words: is it possible to get Notifications slide down when app in background mode? Similar what WhatsApp do when I'm not in app.

I set option android_priority=2 when send push-notification via remote-api, and push-history show that this option pass to pushwoosh server. And notification received by device. But it just show small icon on top of screen. And I want something similar to iOS notifications. Is it possible with this plugin?

**Comment by shaders** [comment]
I'm not sure what you talking about. Could you post a screenshot maybe?

**Comment by antonvovchenko** [comment]
![img_6371](https://cloud.githubusercontent.com/assets/350678/8880562/61bf8c9c-3242-11e5-80fe-10cf4503079c.JPG)
![img_6370](https://cloud.githubusercontent.com/assets/350678/8880564/649d0016-3242-11e5-9cab-215e88badc35.JPG)

Here are two screenshots: one with notification message from Viber app, and another by WhatsApp.
Any advices how to do something similar for Android using Pushwoosh?

Thanks you.

**Comment by shaders** [comment]
Hi, just use android priority (set to MAX) from the control panel or remote API. It works properly now.
