### ISSUE TITLE
Phonegap Build builds failing

### ISSUE THREAD

**Issue by gabaum10** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#115]
It seems a change last night at some point totally broke Phonegap Build for both iOS and Android.  This looks potentially related to https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/commit/be76ad9f7b184935ff44916dc9cb137b217e81c4.  I am attaching the point of failure from the build logs below.  

**Android**:
-compile:
    [javac] Compiling 36 source files to /project/bin/classes
    [javac] /project/src/com/pushwoosh/plugin/pushnotifications/PushNotifications.java:349: error: cannot find symbol
    [javac] 		PushManager.sendLocation(cordova.getActivity(), location);
    [javac] 		           ^
    [javac]   symbol:   method sendLocation(Activity,Location)
    [javac]   location: class PushManager
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

BUILD FAILED
/home/ec2-user/android-sdk/tools/ant/build.xml:716: The following error occurred while executing this line:
/home/ec2-user/android-sdk/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.

Total time: 6 seconds

/project/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: release,-f,/project/build.xml

**iOS**: 
Ld build/VeociSTAGE.build/Release-iphoneos/VeociSTAGE.build/Objects-normal/arm64/VeociSTAGE normal arm64
    cd /project
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -L/project/build -L/project/VeociSTAGE/Plugins/com.pushwoosh.plugins.pushwoosh -F/project/build -filelist /project/build/VeociSTAGE.build/Release-iphoneos/VeociSTAGE.build/Objects-normal/arm64/VeociSTAGE.LinkFileList -dead_strip -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=6.0 -framework AssetsLibrary /project/build/libCordova.a -framework CoreGraphics -framework MobileCoreServices -liconv -framework AVFoundation -framework CoreVideo -framework QuartzCore -framework CoreImage -framework AudioToolbox -weak_framework ImageIO -framework CoreLocation -weak_framework SystemConfiguration /project/VeociSTAGE/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh -framework Security -framework Storekit -Xlinker -dependency_info -Xlinker /project/build/VeociSTAGE.build/Release-iphoneos/VeociSTAGE.build/Objects-normal/arm64/VeociSTAGE_dependency_info.dat -o /project/build/VeociSTAGE.build/Release-iphoneos/VeociSTAGE.build/Objects-normal/arm64/VeociSTAGE
Undefined symbols for architecture arm64:
  "_deflate", referenced from:
      pushwoosh::zipWriteInFileInZip(void*, void const*, unsigned int) in Pushwoosh(zip.o)
      pushwoosh::zipCloseFileInZipRaw(void*, unsigned long, unsigned long) in Pushwoosh(zip.o)
  "_inflate", referenced from:
      pushwoosh::unzReadCurrentFile(void*, void*, unsigned int) in Pushwoosh(unzip.o)
  "_deflateInit2_", referenced from:
      pushwoosh::zipOpenNewFileInZip3(void*, char const*, pushwoosh::zip_fileinfo const*, void const*, unsigned int, void const*, unsigned int, char const*, int, int, int, int, int, int, char const*, unsigned long) in Pushwoosh(zip.o)
  "_deflateEnd", referenced from:
      pushwoosh::zipCloseFileInZipRaw(void*, unsigned long, unsigned long) in Pushwoosh(zip.o)
  "_inflateInit2_", referenced from:
      pushwoosh::unzOpenCurrentFile3(void*, int*, int*, int, char const*) in Pushwoosh(unzip.o)
  "_inflateEnd", referenced from:
      pushwoosh::unzCloseCurrentFile(void*) in Pushwoosh(unzip.o)
  "_crc32", referenced from:
      -[PWZipArchive addFileToZip:newname:] in Pushwoosh(PWZipArchive.o)
      pushwoosh::unzReadCurrentFile(void*, void*, unsigned int) in Pushwoosh(unzip.o)
      pushwoosh::zipWriteInFileInZip(void*, void const*, unsigned int) in Pushwoosh(zip.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld build/VeociSTAGE.build/Release-iphoneos/VeociSTAGE.build/Objects-normal/arm64/VeociSTAGE normal arm64
(1 failure)

**Comment by gabaum10** [comment]
Confirmed.  Forcing the PGB to use version 3.5.9 builds successfully.

**Comment by DimanAM** [comment]
I've published latest commit to npm - pushwoosh-cordova-plugin@3.6.0-1. PGB should work now.

**Comment by shaders** [comment]
now fixed for iOS too.
