### ISSUE TITLE
Trouble building - Cordova iOS

### ISSUE THREAD

**Issue by rknell** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#116]
Hi All,

Android is building well, iOS fails to build both with `cordova build ios` and firing the project up in xcode and trying to build there. If I remove the pushwoosh plugin it builds fine.

iOS version is 3.8.0

Not sure what you need to debug, but here is a screenshot:

<img width="1050" alt="screen shot 2015-08-13 at 9 44 10 am" src="https://cloud.githubusercontent.com/assets/5875053/9239534/f8f6caf0-419f-11e5-95fa-27c55b3201d9.png">

Any help is much appreciated!

**Comment by rknell** [comment]
So what worked for me was adding the libz.dylib to the "link binary with libraries" section under Build Phases, and then I also added -lstdc++ flag to Build Settings > Linking > Other Linker Flags

**Comment by DimanAM** [comment]
Fixed by https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/commit/7251edbbc1890bb596b4548cef369ff1a4227e09
