### ISSUE TITLE
Plugin incompatibility

### ISSUE THREAD

**Issue by chancezeus** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#117]
Currently the plugin.xml defines:

```
<source-file src="src/android/lib/android-support-v4.jar" target-dir="libs" />
<source-file src="src/android/lib/google-play-services.jar" target-dir="libs" />
```

which causes incompatibility issues with plugins that for example implement admob/analytics, the proper way to include these libraries is (as far as I know):

```
<framework src="com.google.android.gms:play-services:+" />
<framework src="com.android.support:support-v4:+" />
```

Hope this can get resolved soon (and in the meantime helps anyone who has issues with duplicate definition errors in the dex phase of compilation)...

**Comment by DimanAM** [comment]
Fixed.
Thanks for reporting this issue.
