### ISSUE TITLE
3.6.5 No longer builds on PhoneGap Build

### ISSUE THREAD

**Issue by dkolar** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#118]
When the PhoneGap Build service uses version 3.6.5 of the plugin (using `<gap:plugin name="pushwoosh-cordova-plugin" source="npm" />`), the build fails. Forcing it to use version 3.6.4 fixes the issue and allows it to build again.

The build error is...
`BUILD FAILED
/home/ec2-user/android-sdk/tools/ant/build.xml:573: ../../../../../../home/ec2-user/android-sdk/com.google.android.gms:play-services-gcm:+ resolve to a path with no project.properties file for project /project`

**Comment by shaders** [comment]
Posted an issue on PGB. Let's see what they reply.
http://community.phonegap.com/nitobi/topics/phonegap-build-fails-how-to-add-google-play-servies?rfm=1

Pls up the ticket if you can.

**Comment by khurana3192** [comment]
I just added this plugin in my ionic app and it is not allowing me to build the app!
I think the latest version has some issue. How can I specifically use version 3.6.4 in my ionic App?

**Comment by dkolar** [comment]
@khurana3192 I am still using 3.6.3 at the moment and it is working with PhoneGap Build. Here is the config line:

`<gap:plugin name="pushwoosh-cordova-plugin" source="npm" version="3.6.3" />`

...where "version" contains the version number you want to use. On your app's page on build.phonegap.com, under the Plugins tab, you should be able to see which version it read from the config file.

**Comment by shaders** [comment]
Since PGB guys don't really do anything about this error, another plugin that is compatible with PGB (references jar files instead of declaring dependencies) was uploaded. Use it like this:
````
    <gap:plugin name="pushwoosh-pgb-plugin" source="npm" />
````
