### ISSUE TITLE
ld: framework not found Pushwoosh

### ISSUE THREAD

**Issue by alexbleks** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#122]
![screen shot 2015-09-16 at 13 17 22](https://cloud.githubusercontent.com/assets/720857/9903256/4e6ed8de-5c75-11e5-8b71-d79df2f53ca5.png)
ld: framework not found Pushwoosh
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by shaders** [comment]
Did you try to reinstall the plugin? Which plugin version do you use?

**Comment by freddiescott** [comment]
Hi,

I'm getting the same error but I'm using the Telerik AppBuilder build service.
I've installed the latest version of the javascript SDK : v3.6.10

Here is a snippet from the return messages from the build service.
```
Error: [xcode-build] Link /tmp/builds/TuibMGbYUb7HFVbJlz/app/DerivedData/Cordova400/Build/Intermediates/Cordova400.build/Release-iphoneos/Cordova400.build/Objects-normal/arm64/Cordova400: ld: framework not found Pushwoosh
clang: error: linker command failed with exit code 1 (use -v to see invocation)
	Error: [xcode-build] Link /tmp/builds/TuibMGbYUb7HFVbJlz/app/DerivedData/Cordova400/Build/Intermediates/Cordova400.build/Release-iphoneos/Cordova400.build/Objects-normal/armv7/Cordova400: ld: framework not found Pushwoosh
clang: error: linker command failed with exit code 1 (use -v to see invocation)
	Error: Buld failed
```

Working with the 3.4.13 version does not give the same error.

**Comment by freddiescott** [comment]
I also checked the 3.2.1 version of the cordova plugin and that one also produces the ld: framework not found Pushwoosh during the build process. The messages are the same as my previous comment.

**Comment by shaders** [comment]
Could you try with the latest plugin version? this should work.

**Comment by jlstr** [comment]
Hello, Why is this issue closed? I have the same problem but I don't see a solution for it here. If the solution is to download the latest plugin, then what are the exact steps to do it?
-Thanks

**Comment by jlstr** [comment]
Hello @shaders, I was hoping you could respond to this issue. This error will not go away once you add the **Pushwoosh.framework** inside XCode.
Thank you
