### ISSUE TITLE
64-bit Support & iOS 9

### ISSUE THREAD

**Issue by sandstrom** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#124]
We've run into an issue submitting an iOS 9 App (see photo below). Removing the Pushwoosh Cordova plugin solves the problem. Using the `3.6.5` version (linked directly from Github).

A wild guess is that the issue is with your binary code not supporting `arm64`.

![5rpq7](https://cloud.githubusercontent.com/assets/122287/9946147/bbd25cc6-5d91-11e5-8074-c6f433939f3a.png)

*itms-90086 Missing 64-bit support*

**Comment by sandstrom** [comment]
**I'm not sure about this anymore.**

The Cordova build-process is fickle and I don't trust it. It's possible that something else cause this issue. Feel free to close if you think Pushwoosh Cordova plugin is already 64-bit compatible.

**Comment by shaders** [comment]
It looks like you have to specify arm64 architecture in Cordova XCode project. Pushwoosh supports 64bit architecture since ages. Meanwhile Cordova Plugin with iOS9 (bitcode) for XCode 7 update should be live today.
