### ISSUE TITLE
Intel XDK v2496 and Pushwoosh 3.6.5 builds failing

### ISSUE THREAD

**Issue by tysjiang** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#126]
Intel XDK released a new version v2496, which actually features Pushwoosh prominently as a featured plugin for push notifications.  Unfortunately, when selecting the latest version available on it 3.6.5 it fails to build for Android Cordova.  
(note: it works for the iOS builds)

**Comment by shaders** [comment]
The error you see is a known issue:
Could not find any version that matches com.google.android.gms:play-services-gcm:+.

And is a known bug of Phonegap Build:
https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/issues/118

To workaround this you can use previous version of the plugin: 3.6.4
It works.

**Comment by tysjiang** [comment]
hm... tried 3.6.4, it did not build either

**Comment by shaders** [comment]
It does. Just tried it here. What is your error?

Note that you need to reupload the project (close build page, select Android Build, upload changes). Also min android API is 14.

**Comment by dkolar** [comment]
Does this blog post indicate that Adobe is addressing the root cause of the issue? http://phonegap.com/blog/2015/09/28/android-using-gradle/

**Comment by shaders** [comment]
Just use PGB compatible Pushwoosh plugin as outlined above (in 118 ticket):

        <gap:plugin name="pushwoosh-pgb-plugin" source="npm" />

This one:
https://www.npmjs.com/package/pushwoosh-pgb-plugin
