### ISSUE TITLE
Over 200 warning on ios 

### ISSUE THREAD

**Issue by zaouifahd** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#127]
Hi, when installed plugin have over 200 warning, anyone can help me please ?

Message : 
GenerateDSYMFile /Users/Fahed/Library/Developer/Xcode/DerivedData/Trice-gmfhlcyicrqteheazgzdbuyarita/Build/Products/Debug-iphoneos/Trice.app.dSYM /Users/Fahed/Library/Developer/Xcode/DerivedData/Trice-gmfhlcyicrqteheazgzdbuyarita/Build/Products/Debug-iphoneos/Trice.app/Trice
    cd /Users/Fahed/Desktop/Application/Trice/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/Fahed/Library/Developer/Xcode/DerivedData/Trice-gmfhlcyicrqteheazgzdbuyarita/Build/Products/Debug-iphoneos/Trice.app/Trice -o /Users/Fahed/Library/Developer/Xcode/DerivedData/Trice-gmfhlcyicrqteheazgzdbuyarita/Build/Products/Debug-iphoneos/Trice.app.dSYM

while processing /Users/Fahed/Desktop/Application/Trice/platforms/ios/Trice/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(RichPushLabel.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/1QT5W6HUSAVW4/UIKit-16ZVZGT9B0NX3.pcm: No such file or directory
while processing /Users/Fahed/Desktop/Application/Trice/platforms/ios/Trice/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(RichPushLabel.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/1QT5W6HUSAVW4/UIKit-16ZVZGT9B0NX3.pcm: No object file for requested architecture
while processing /Users/Fahed/Desktop/Application/Trice/platforms/ios/Trice/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(RichPushLabel.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/1QT5W6HUSAVW4/Foundation-9CVH0LLUQLB5.pcm: No such file or directory
while processing /Users/Fahed/Desktop/Application/Trice/platforms/ios/Trice/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(RichPushLabel.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/1QT5W6HUSAVW4/Foundation-9CVH0LLUQLB5.pcm: No object file for requested architecture
while processing /Users/Fahed/Desktop/Application/Trice/platforms/ios/Trice/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(RichPushLabel.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/1QT5W6HUSAVW4/CoreGraphics-35UZER482591G.pcm: No such file or directory
while processing /Users/Fahed/Desktop/Application/Trice/platforms/ios/Trice/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(RichPushLabel.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/1QT5W6HUSAVW4/CoreGraphics-35UZER482591G.pcm: No object file for requested architecture
while processing /Users/Fahed/Desktop/Application/Trice/platforms/ios/Trice/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(RichPushLabel.o):
warning: Could not resolve external type c:objc(cs)UILabel
while processing /Users/Fahed/Desktop/Application/Trice/platforms/ios/Trice/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(RichPushLabel.o):
warning: Could not resolve external type c:@S@CGRect
while processing /Users/Fahed/Desktop/Application/Trice/platforms/ios/Trice/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(NSString+StripHtmlTagsAndQuotes.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/1QT5W6HUSAVW4/Foundation-9CVH0LLUQLB5.pcm: No such file or directory
while processing /Users/Fahed/Desktop/Application/Trice/platforms/ios/Trice/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(NSString+StripHtmlTagsAndQuotes.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/1QT5W6HUSAVW4/Foundation-9CVH0LLUQLB5.pcm: No object file for requested architecture
while processing /Users/Fahed/Desktop/Application/Trice/platforms/ios/Trice/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(NSString+StripHtmlTagsAndQuotes.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/1QT5W6HUSAVW4/UIKit-16ZVZGT9B0NX3.pcm: No such file or directory
while processing /Users/Fahed/Desktop/Application/Trice/platforms/ios/Trice/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(NSString+StripHtmlTagsAndQuotes.o):
warning: /var/folders/ll/dm7834z979z56_tbc7rr__j40000gp/C/org.llvm.clang.jenkins/ModuleCache/1QT5W6HUSAVW4/UIKit-16ZVZGT9B0NX3.pcm: No object file for requested architecture
while processing /Users/Fahed/Desktop/Application/Trice/platforms/ios/Trice/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(NSString+StripHtmlTagsAndQuotes.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/Fahed/Desktop/Application/Trice/platforms/ios/Trice/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(NSString+StripHtmlTagsAndQuotes.o):
warning: Could not resolve external type c:objc(cs)NSArray
while processing /Users/Fahed/Desktop/Application/Trice/platforms/ios/Trice/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(NSString+StripHtmlTagsAndQuotes.o):
warning: Could not resolve external type c:objc(cs)NSRegularExpression
while processing /Users/Fahed/Desktop/Application/Trice/platforms/ios/Trice/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(NSString+StripHtmlTagsAndQuotes.o):

**Comment by shaders** [comment]
Hi, It's a bug of XCode 7. You need to change debug information from DWARF + dSYM to DWARF.

See more information here: https://community.pushwoosh.com/questions/2774/lot-of-warnings-with-xcode-70-and-pushwoosh-304

**Comment by luizperes** [comment]
Thank you @shaders, It helped a lot on my project, man! :D
