### ISSUE TITLE
iOS question/feature: Get notification(s) when app is resumed

### ISSUE THREAD

**Issue by zarko-tg** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#128]
The 'push-notification' event does not trigger when a push arrives while an application is in background.
How can we obtain the push notification(s) when the user puts the app into foreground (for example by choosing to open the app through its icon)?
It seems that on Android we can achieve this by using the getPushHistory function but how about iOS?

I am hoping for an answer that is not in the lines of 'this is by design on iOS'.

Thanks

**Comment by shaders** [comment]
> I am hoping for an answer that is not in the lines of 'this is by design on iOS'.

Unfortunately it is. When push notification arrives and the app is in background iOS does not execute the code of the app. And there is no API (at least public) for Notification Center.

As a workaround at the moment you can use silent aka "newsstand" push that will be delivered by iOS to the app in the background. This technique is outlined in the following guide:
http://docs.pushwoosh.com/docs/deletable-ios-push

**Comment by zarko-tg** [comment]
As far as I can remember this is not an issue for example in UrbanAirship:
https://github.com/urbanairship/phonegap-ua-push/blob/master/Example/index.html#L57
