### ISSUE TITLE
crash on init

### ISSUE THREAD

**Issue by alexbleks** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#131]
When I initialize android push, the app crashes and leaves me this message:
I have latest PW installed.

I/Pushwoosh(22116): [PushManager] App ID: BAF43-C5EFD
I/Pushwoosh(22116): [PushManager] Project ID: 591548188312
I/Pushwoosh(22116): [PushManager] This is android device
W/ActivityManager( 1010): Unable to start service Intent { cmp=com.MyApp.Appis/com.pushwoosh.inapp.InAppRetrieverService } U=0: not found
W/Pushwoosh(22116): [RequestManager] Try To sent: registerUser
V/Pushwoosh(22116): [PushRegistrarGCM] number of receivers for com.MyApp.Appis: 3
V/Pushwoosh(22116): [PushRegistrarGCM] Found 1 receivers for action com.google.android.c2dm.intent.RECEIVE
W/PluginManager(22116): THREAD WARNING: exec() call to PushNotification.onDeviceReady blocked the main thread for 38ms. Plugin should use CordovaInterface.getThreadPool().
D/PushNotifications(22116): Plugin Called
I/dalvikvm(22116): Could not find method com.google.android.gms.iid.InstanceID.getInstance, referenced from method com.pushwoosh.GCMRegistrationService.register
W/dalvikvm(22116): VFY: unable to resolve static method 9807: Lcom/google/android/gms/iid/InstanceID;.getInstance (Landroid/content/Context;)Lcom/google/android/gms/iid/InstanceID;
D/dalvikvm(22116): VFY: replacing opcode 0x71 at 0x0008
I/dalvikvm(22116): Could not find method com.google.android.gms.iid.InstanceID.getInstance, referenced from method com.pushwoosh.GCMRegistrationService.unregister
W/dalvikvm(22116): VFY: unable to resolve static method 9807: Lcom/google/android/gms/iid/InstanceID;.getInstance (Landroid/content/Context;)Lcom/google/android/gms/iid/InstanceID;
D/dalvikvm(22116): VFY: replacing opcode 0x71 at 0x0007
V/Pushwoosh(22116): [com.pushwoosh.GCMRegistrationService] Intent action = com.pushwoosh.gcm.intent.REGISTER
W/dalvikvm(22116): threadid=28: thread exiting with uncaught exception (group=0x416ebd40)
E/AndroidRuntime(22116): FATAL EXCEPTION: IntentService[com.pushwoosh.GCMRegistrationService]
E/AndroidRuntime(22116): Process: com.MyApp.Appis, PID: 22116
E/AndroidRuntime(22116): java.lang.NoClassDefFoundError: com.google.android.gms.iid.InstanceID
E/AndroidRuntime(22116): 	at com.pushwoosh.GCMRegistrationService.register(Unknown Source)
E/AndroidRuntime(22116): 	at com.pushwoosh.GCMRegistrationService.onHandleIntent(Unknown Source)
E/AndroidRuntime(22116): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/AndroidRuntime(22116): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(22116): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(22116): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/ActivityManager( 1010):   Force finishing activity com.MyApp.Appis/.MainActivity
W/Pushwoosh(22116): [RequestManager] Pushwoosh Request: {"request":{"hwid":"56cdf15f3b031e0b","v":"3.0.1.529","application":"BAF43-C5EFD","userId":"56cdf15f3b031e0b"}}
W/Pushwoosh(22116): [RequestManager] Pushwoosh Request To: https://cp.pushwoosh.com/json/1.3/registerUser

**Comment by DimanAM** [comment]
Please make sure your Google Play services and Android Support libraries in Android SDK are up to date.

**Comment by yves-s** [comment]
All my libraries are up to date but I still get the error message:
```bash
ActivityManager: Unable to start service Intent { cmp=de.aboutyou.mobile.app/com.pushwoosh.inapp.InAppRetrieverService } U=0: not found
```

```bash
04-11 17:04:24.236 24093 24194 I Pushwoosh: [PushManager] App ID: D7DAF-3CE66
04-11 17:04:24.237 24093 24194 I Pushwoosh: [PushManager] Project ID: 555458305584
04-11 17:04:24.238 24093 24194 I Pushwoosh: [PushManager] This is android device
04-11 17:04:24.256  1213  5554 W ActivityManager: Unable to start service Intent { cmp=de.aboutyou.mobile.app/com.pushwoosh.inapp.InAppRetrieverService } U=0: not found
04-11 17:04:24.256 24093 24219 D Pushwoosh: [RequestManager] Try To send: registerUser
04-11 17:04:24.272 24093 24194 V Pushwoosh: [PushRegistrarGCM] number of receivers for de.aboutyou.mobile.app: 5
04-11 17:04:24.274 24093 24194 V Pushwoosh: [PushRegistrarGCM] Found 1 receivers for action com.google.android.c2dm.intent.RECEIVE
04-11 17:04:24.285 24093 24194 W PluginManager: THREAD WARNING: exec() call to PushNotification.onDeviceReady blocked the main thread for 102ms. Plugin should use CordovaInterface.getThreadPool().
04-11 17:04:24.291 24093 24093 I chromium: [INFO:CONSOLE(1602)] "Not iOS registerOnStart", source: file:///android_asset/www/js/main.js (1602)
04-11 17:04:24.291 24093 24194 D PWCordovaPlugin: Plugin Method Called: registerDevice
04-11 17:04:24.298 24093 24223 V Pushwoosh: [GCMRegistrationService] Intent action = com.pushwoosh.gcm.intent.REGISTER
04-11 17:04:24.316 24093 24194 F Adjust  : PRODUCTION: Adjust is running in Production mode. Use this setting only for the build that you want to publish. Set the environment to `sandbox` if you want to test your app!
04-11 17:04:24.336 24093 24194 W PluginManager: THREAD WARNING: exec() call to Adjust.create blocked the main thread for 36ms. Plugin should use CordovaInterface.getThreadPool().
04-11 17:04:24.338 24093 24194 V StatusBar: Executing action: styleBlackOpaque
04-11 17:04:24.658 24093 24223 W InstanceID/Rpc: Found 10013
04-11 17:04:24.712 24093 24219 I Pushwoosh: [RequestManager]
04-11 17:04:24.712 24093 24219 I Pushwoosh: x
04-11 17:04:24.712 24093 24219 I Pushwoosh: |     Pushwoosh request:
04-11 17:04:24.712 24093 24219 I Pushwoosh: | Url: https://cp.pushwoosh.com/json/1.3/registerUser
04-11 17:04:24.712 24093 24219 I Pushwoosh: | Payload: {"request":{"v":"3.3.3.613","device_type":3,"application":"D7DAF-3CE66","hwid":"821467ebcd4b2fa7","userId":"821467ebcd4b2fa7"}}
04-11 17:04:24.712 24093 24219 I Pushwoosh: | Response: {"status_code": 200, "status_message": "OK","response":null}
04-11 17:04:24.712 24093 24219 I Pushwoosh: x
```

**Comment by shaders** [comment]
That's harmless message. 
If you want to use In-App Messages functionality of Pushwoosh you'll need to add this service to your manifest as per:
http://docs.pushwoosh.com/docs/androidmanifestxml-modifications#in-app-messages
http://docs.pushwoosh.com/docs/in-app-messages

**Comment by yves-s** [comment]
Thanks for the clarification @shaders. So that shouldn't be the problem why I don't get notifications.

**Comment by shaders** [comment]
@yves-s that's correct. Do you see registerDevice function call in the logs?
Also when you send push notifications you should check push history for the push status.
