### ISSUE TITLE
ios packaging failing because bitcode

### ISSUE THREAD

**Issue by mccraigmccraig** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#132]
i'm seeing bitcode related errors when packaging for iOS with pushwoosh cordova plugin version `com.pushwoosh.plugins.pushwoosh 3.6.11 "Pushwoosh"` and `XCode 7.0.1`

```
ld: bitcode bundle could not be generated because '/Users/mccraig/dev/employeerepublic/repos/mobile/yapster-ionic/platforms/ios/Yapster/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(PWBaseTracker.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

this seems similar to https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/issues/123 , although the original issue was meant to be fixed in `pushwoosh-phonegap-3.0-plugin v3.6.6` afaics

**Comment by shaders** [comment]
Hi,

Could you make sure that you are using 3.6.11 plugin version?

What is the size of the file?

    /Users/mccraig/dev/employeerepublic/repos/mobile/yapster-ionic/platforms/ios/Yapster/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh

And this file?

    /Users/mccraig/dev/employeerepublic/repos/mobile/yapster-ionic/plugins/com.pushwoosh.plugins.pushwoosh/src/ios/Pushwoosh.framework/Versions/A/Pushwoosh

And what is the last modification date? It looks like somehow the framework was not updated. As 3.6.11 plugin version does include the bitcode (just double checked).

**Comment by mccraigmccraig** [comment]
i did remove and re-add the plugin in case it was something like that. here are the file-sizes -

```
qluupp:➜  yapster-ionic git:(master) ✗ % ls -al platforms/ios/Yapster/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh
-rw-r--r--  1 mccraig  staff  9791576 16 Oct 19:44 platforms/ios/Yapster/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh
```

```
qluupp:➜  yapster-ionic git:(master) ✗ % ls -al plugins/com.pushwoosh.plugins.pushwoosh/src/ios/Pushwoosh.framework/Versions/A/Pushwoosh
-rw-r--r--  1 mccraig  staff  9791576 15 Oct 14:40 plugins/com.pushwoosh.plugins.pushwoosh/src/ios/Pushwoosh.framework/Versions/A/Pushwoosh
```

**Comment by shaders** [comment]
The size is correct. Could you pls confirm you still see the same error?

**Comment by mccraigmccraig** [comment]
yep, just re-enabled bitcode and ran an archive build - same error 

https://www.evernote.com/l/AD7ANNvvlllGH6k9H-gGUsdZ1r2qQuaNpDg

last comment on #123 seemed to indicate it may be only `Xcode 7.0.1` generating the error - i am on `Version 7.0.1 (7A1001)`

**Comment by shaders** [comment]
I'm on XCode 7.0.1, however I see the linker flags a bit different here.
Any chance you could zip and send me your project? Pls remove "www" directory from it (I don't need your sources :).

**Comment by mccraigmccraig** [comment]
sure - where shall i send ?

**Comment by shaders** [comment]
Could you paste as dropbox link?

**Comment by mccraigmccraig** [comment]
yep, uploading now - will take about 15 mins on my crappy dsl

**Comment by mccraigmccraig** [comment]
@shaders oops. i forgot about it :) - here's the link

https://www.dropbox.com/s/9lcc3d1663jtcjn/yapster-ionic-copy.tgz?dl=0

**Comment by shaders** [comment]
reproduced the behavior, checking for the solution

**Comment by mccraigmccraig** [comment]
awesome, thanks - can i kill the dropbox link now ?

**Comment by shaders** [comment]
Yes, found the problem. The library has to be built now with an additional flag. Will run and publish a build tomorrow.
