### ISSUE TITLE
registerDevice error callback not fired when push notifications disabled in settings IOS

### ISSUE THREAD

**Issue by vik-buchinski** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#134]
So, problem: "registerDevice error callback not fired when push notifications disabled in settings IOS"
How to repeat:
Disable application push notifications in phone settings.
Try to register device.
Result: no error and success callback fired.
If need, later i will write OS version.
Device: iphone 5

**Comment by shaders** [comment]
That's normal behavior since iOS gives you push token. You can use this token later when user re-enables push notification in settings without requiring user to open your app again.

The only way you will not receive push token is the following:
1. Fresh install (or previous app install has notification disabled in settings)
2. User presses "NO" on Allow notification alert
3. The app is not configured for "Background refresh" in Info.plsit

**Comment by vik-buchinski** [comment]
I think it is not normal behavior, because in common cases when you call function and pass inside this function(registerDevice) 2 callbacks error and success you are expecting that one of callbacks will fire. But in my case no one callback function is not fired. I think it is bug.

**Comment by shaders** [comment]
I see you mean no callbacks are fired at all. Let me check.

**Comment by vik-buchinski** [comment]
Yes, i mean this. No callback fired at all.

**Comment by shaders** [comment]
One more thing: when alert "allow notifications" has been displayed - did you press yes?
Then disabled notifications in settings?

**Comment by vik-buchinski** [comment]
Yes

**Comment by vik-buchinski** [comment]
But when i installed app first time and not opened it, then disable push notifications in setting there are was the same behaviour as previous.

**Comment by shaders** [comment]
Thanks. Checking.

**Comment by shaders** [comment]
Ok. Here are the results. Unfortunately as I suspected this is iOS documented behavior. Here is the description from the iOS header file:

// Calling this will result in either application:didRegisterForRemoteNotificationsWithDeviceToken: or application:didFailToRegisterForRemoteNotificationsWithError: to be called on the application delegate. Note: these callbacks will be made only if the application has successfully registered for user notifications with registerUserNotificationSettings:, or if it is enabled for Background App Refresh.
- (void)registerForRemoteNotifications NS_AVAILABLE_IOS(8_0);

This means effectively that if you disable app notifications no callback (no success, no error) would be made to the app by iOS. Therefore the plugin simply have nothing to return. The delegate calls has not been made by iOS to the plugin.
You have to program your app logic to take this behavior into account.

I'm sorry, this is documented iOS behavior.

**Comment by AzatiMob** [comment]
It is sad... But why phonegap pushwoosh plugin 3.4.1 calling error callback in such case?

**Comment by vik-buchinski** [comment]
It is sad... But why phonegap pushwoosh plugin 3.4.1 calling error callback in such case?

**Comment by shaders** [comment]
What is iOS version do you have? Did you check 3.4.1 on the same iOS version? What I see from debugging iOS9 is that no callback has been called at all from OS.

**Comment by vik-buchinski** [comment]
IOS 8.3 plugin version 3.4.1 here is next behavior: at first executed success callback next error callback. Maybe for fix this issue in ios while executing function "registerDevice" check if push notifications is available for current app, if not - call error callback?
http://stackoverflow.com/questions/1535403/determine-on-iphone-if-user-has-enabled-push-notifications

**Comment by vik-buchinski** [comment]
For history.. I am created plugin for checking push notifications enabled/disabled in phone settings
https://www.npmjs.com/package/push_status
