### ISSUE TITLE
Plugin conflict with Google analytics (and possibly facebook connect)

### ISSUE THREAD

**Issue by jobberteamcarolo** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#136]
Hi,
We are using pushwoosh plugin and google-analytics plugin on Phonegap Build for our app.
For some reason, there is a conflict between theses 2 plugins (and with facebook connect too according to other issues).

PGB staff tracked down the problem on my topic : 
http://community.phonegap.com/nitobi/topics/pgb-fail-conflict-plugins-between-google-analytics-pushwoosh-pgb-plugin-only-android

"The Google Analytics and Pushwoosh plugins reference different versions of the Android Support library, causing the conflict. You'll most likely have to remove one of those plugins to get it to work."

Our app is in beta and we are officially launching it this week but we don't want to launch it without one of the plugin.

Any help would be appreciated,
Romain.

**Comment by DimanAM** [comment]
You can use pushwoosh-cordova-plugin instead of pushwoosh-pgb-plugin. This should solve the problem:
<preference name="android-build-tool" value="gradle" /> 
<gap:plugin name="pushwoosh-cordova-plugin" source="npm" />
