### ISSUE TITLE
android push message replace previous

### ISSUE THREAD

**Issue by xale76** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#137]
Hello, in Android, when I receive 2 pushes in row, (preview in taskbar) the latest always deletes the first and when I open the app by clicking on it, the first push in not handled.
What's wrong?
I use pushwoosh cordova plugin version 3.5.9

**Comment by DimanAM** [comment]
You should call [setMultiNotificationMode](https://rawgit.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/master/Documentation/files/PushNotification-js.html#PushNotification.setMultiNotificationMode) if you want several notifications to be displayed in taskbar.
