### ISSUE TITLE
default ttl

### ISSUE THREAD

**Issue by xale76** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#138]
hello what's the ttl for android and ios for default? thx

**Comment by shaders** [comment]
android default ttl is 4 weeks
ios default ttl is 186400 seconds

**Comment by xale76** [comment]
Thx but the max values?

**Comment by shaders** [comment]
As per Apple doc:
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html

A UNIX epoch date expressed in seconds (UTC) that identifies when the notification is no longer valid and can be discarded. - 4 bytes

Android is:
The value of this parameter must be a duration from 0 to 2,419,200 seconds

Basically it means you can ask Apple/Google to keep your message for years, however I doubt that it will be really kept on the servers for that long.

**Comment by xale76** [comment]
Ok...because I have this problem: I send pushes by cordova. My json push object doesn't have ios_ttl and android_gcm_ttl property at all so I expect a default ttl...but if I send push and I'm not logged in the app when I log (after 5/10 mins) I don't receive the push sent as expected...what's wrong?

**Comment by shaders** [comment]
The discussion moved to the https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/issues/139
