### ISSUE TITLE
linker error armv7s

### ISSUE THREAD

**Issue by pmariano** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#140]
When try to release with cordova command: `cordova build ios --release --device` just throw:

```
....
/Users/pmariano/projects/lua/takeshi/platforms/ios/LUA.NET/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh -framework Security -framework Storekit -lstdc++ -lz -Xlinker -dependency_info -Xlinker /Users/pmariano/projects/lua/takeshi/platforms/ios/build/LUA.NET.build/Release-iphoneos/LUA.NET.build/Objects-normal/armv7s/LUA.NET_dependency_info.dat -o /Users/pmariano/projects/lua/takeshi/platforms/ios/build/LUA.NET.build/Release-iphoneos/LUA.NET.build/Objects-normal/armv7s/LUA.NET
ld: file is universal (4 slices) but does not contain a(n) armv7s slice: /Users/pmariano/projects/lua/takeshi/platforms/ios/LUA.NET/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh file '/Users/pmariano/projects/lua/takeshi/platforms/ios/LUA.NET/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh' for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
```
The following build commands failed:
	Ld build/LUA.NET.build/Release-iphoneos/LUA.NET.build/Objects-normal/armv7s/LUA.NET normal armv7s
(1 failure)
```

If I remove the Pushwoosh plugin the build finishes successfully, any idea?

Cordova Version: 5.4.0
Xcode: 7.1.1 (7B1005)
com.pushwoosh.plugins.pushwoosh 3.6.15

**Comment by shaders** [comment]
armv7s has been dropped from the list of standard architectures since XCode 6
Feel free to remove "armv7s" architecture from your project.

**Comment by pmariano** [comment]
@shaders thanks for the answer.

Unfortunately cordova don't support  to change default architectures. 

Anyone with the same problem with cordova build can use the below cordova hook. It manually removes armv7s from build script.

Add it on `hooks/after_platform_add/`

```
#!/bin/sh

FILE=platforms/ios/cordova/lib/build.js

if test -f "$FILE"; then
  sed -i $FILE -e 's,armv7s,,g'
  exit 0
fi
````

**Comment by shaders** [comment]
I can see Cordova adds this platform only when you build from the command line. It is not present when you build Xcode project via XCode. I'll add armv7s slice to the Pushwoosh library.

**Comment by shaders** [comment]
This has been fixed in 
https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/commit/6df63af7da312a6cfdf25bb49ce45b7ea04cde42
