### ISSUE TITLE
Plugin not updated at Phonegap Build plugins for Apple ATS iOS9 restrictions

### ISSUE THREAD

**Issue by qmarcos** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#143]
We have updated our app for iOS store and we are being rejected since latest ios 9 update.

After some attempts and debugging our PhoneGap Build bootstrap process, we can confirm the step where our app is blocked is when listen for a response from "registerDevice" method. 

When testing the app during development, and also with developer certificates it works properly (at least in our testing devices), but when the app is reviewed by apple it seems to works different and the initialization of the app is stopped at that point.

So we think the issue is related to App Transport Security... and we found this topic on your forums:
https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/issues/129

It seems you have updated the plugin [in 3.6.9 version](https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/commit/3b19a61088bf41a301ed474a3f6426d5df9a990f) to solve this problem *but the plugin is not updated on Phonegap build repository, as you can see here:*
https://build.phonegap.com/plugins/1297

Fortunately you can specify from where to take it in the config.xml file, changing this line:
`<plugin name="com.pushwoosh.plugins.pushwoosh" spec="3.4.2" source="pgb" />`

with this one:
`<gap:plugin name="pushwoosh-pgb-plugin" source="npm" />`

And this one too for android:
`<preference name="android-build-tool" value="gradle" />`

As is well documented here:
http://docs.pushwoosh.com/docs/phonegap-build

**Comment by DimanAM** [comment]
https://build.phonegap.com/plugins/1297 is deprecated now.

As you mentioned the correct way of including plugin is:
```
<gap:plugin name="pushwoosh-pgb-plugin" source="npm" />
<preference name="android-build-tool" value="gradle" />
```

**Comment by qmarcos** [comment]
Nice job! 
Thanks a lot for your incredible fast response and updating the info at Phonegap build repository.
Hope it helps to others to avoid this nightmare rejecting apps from Apple :)
