### ISSUE TITLE
No such method error

### ISSUE THREAD

**Issue by sean-hill** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#144]
Hey there,

I just upgraded my Pushwoosh plugin to use the latest code. However, on Android whenever I try to register the device, the app crashes with these logs:

	I/chromium( 3961): [INFO:CONSOLE(8453)] "Registering Device for Push", source: file:///android_asset/www/js/app.min.js?v=1.1.3 (8453)
	D/PWCordovaPlugin( 3961): Plugin Method Called: registerDevice
	V/Pushwoosh( 3961): [GCMRegistrationService] Intent action = com.pushwoosh.gcm.intent.REGISTER
	E/AndroidRuntime( 3961): FATAL EXCEPTION: IntentService[GCMRegistrationService]
	E/AndroidRuntime( 3961): Process: com.pingplot.unbill, PID: 3961
	E/AndroidRuntime( 3961): java.lang.NoSuchMethodError: No virtual method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/app/com.pingplot.unbill-1/base.apk)
	E/AndroidRuntime( 3961): 	at com.google.android.gms.iid.zzd.zzdo(Unknown Source)
	E/AndroidRuntime( 3961): 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
	E/AndroidRuntime( 3961): 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
	E/AndroidRuntime( 3961): 	at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
	E/AndroidRuntime( 3961): 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
	E/AndroidRuntime( 3961): 	at com.pushwoosh.GCMRegistrationService.register(Unknown Source)
	E/AndroidRuntime( 3961): 	at com.pushwoosh.GCMRegistrationService.onHandleIntent(Unknown Source)
	E/AndroidRuntime( 3961): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	E/AndroidRuntime( 3961): 	at android.os.Handler.dispatchMessage(Handler.java:102)
	E/AndroidRuntime( 3961): 	at android.os.Looper.loop(Looper.java:145)
	E/AndroidRuntime( 3961): 	at android.os.HandlerThread.run(HandlerThread.java:61)
	V/ApplicationPolicy(  890): isApplicationStateBlocked userId 0 pkgname com.pingplot.unbill

**Comment by shaders** [comment]
Make sure your Android SDK is up to date. In your case Google Play Services library in the Android SDK is outdated and missing necessary methods. All you need to do is to update Android SDK.
