### ISSUE TITLE
android: small banner view show only header

### ISSUE THREAD

**Issue by boynet** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#52]
there are two states for push, the extended and the small(when there is multipile notifications in the bar).
right now when you send push with banner, when the push is in his small view, there is only the header.
I think it also should include the small texts

**Comment by boynet** [comment]
yes sorry for late answerd just wanted to be 100% sure, yes in version 3.4.5.
the small view will contain only header no image or text

**Comment by boynet** [comment]
can you please reopen this issue?

**Comment by shaders** [comment]
Finally fixed in Android SDK 2.9.4
