### ISSUE TITLE
Sencha Touch Android - multiple instances?

### ISSUE THREAD

**Issue by ds8k** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#69]
I'm using the Custom URL Scheme plugin in combination with Pushwoosh to send a URL that will open my app and direct the user to specific areas. This seems to be working fine on iOS but on Android it's creating multiple webviews within the app of the main page. Any ideas? This isn't happening on iOS.

**Comment by shaders** [comment]
Please post a link to the Custom URL Scheme plugin?

**Comment by ds8k** [comment]
https://github.com/EddyVerbruggen/Custom-URL-scheme

**Comment by ds8k** [comment]
Also on Android - when a device receives a notification the initial icon appears to be too large for the space. After the text of the notice rolls away the correct icon is displayed in the task bar.

**Comment by shaders** [comment]
Do you have any sample project exposing this behavior so I could jump start on this?
