### ISSUE TITLE
iOS event.notification object empty

### ISSUE THREAD

**Issue by denza** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#72]
When getting notification title and userdata properties are undefined. This is only problem for iOS, Android version works without problem. It is interesting that  when app is turned off and got notification in iOS notification area you can see title.

**Comment by shaders** [comment]
For iOS layout of push payload differs from android.  
See: https://github.com/Pushwoosh/phonegap-3-sample-app/blob/master/www/js/PushwooshiOS.js

It is: notification.aps.alert

**Comment by denza** [comment]
Works. Thanks.
