### ISSUE TITLE
Platform configuration inconsistencies (`pw_appid` and `appid`)

### ISSUE THREAD

**Issue by cgwyllie** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#73]
Hi,

Just been spending a bit of time trying to figure out why push wasn't working on our iOS app, whilst it was working on Android.

Turned out to be because the app ID configuration parameter is not consistent between platforms.

Could you choose either `appid` or `pw_appid` for all platforms and stick to it?

I appreciate some platforms may require additional configuration keys, but for the core PushWoosh app ID to be inconsistent is quite a nuisance!

Thanks

**Comment by robdick** [comment]
+1

**Comment by shaders** [comment]
You can use "pw_appid" for both iOS and Android.

**Comment by cgwyllie** [comment]
@shaders Ok, great. Are you planning to update the documentation for the hybrid integrations to make it consistent?

**Comment by shaders** [comment]
Finally updated (snail). Thanks!

**Comment by cgwyllie** [comment]
@shaders Great stuff, thanks!
