### ISSUE TITLE
iOS Error Callback Fires Immediately?

### ISSUE THREAD

**Issue by cgwyllie** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#74]
Hi,

When registering for push on iOS, the user is asked for permission to receive push notifications. However, it seems that the error handler is immediately called in the JavaScript SDK just before the dialog is shown to the user.

After the user chooses 'OK' to indicate they would like to receive push notifications, the success callback is fired as expected.

I think might make more sense for the error callback to only be fired after the user has made some choice on the dialog (or in another exceptional circumstance).

Having the error callback trigger right away makes it impossible to use promises in JS to handle the push registration flow, because a promise can only be rejected or resolved once. If the error callback rejects the promise whilst the user is making a choice, the result of a successful registration cannot be propagated to the consumer of the promise.

Here is the console output from the JS side:
```
[Warning] ["failed to register ",null] (app-35b7b8af.js, line 253)
[Warning] push token: [object Object] (app-35b7b8af.js, line 250)
```

And from the Xcode console:
```
2015-01-20 12:21:34.564 Client[216:18919] Will show push notifications alert
2015-01-20 12:21:34.576 Client[216:18919] THREAD WARNING: ['PushNotification'] took '30.371826' ms. Plugin should use a background thread.
2015-01-20 12:21:34.611 Client[216:18919] location services authorization status has not been determined yet
2015-01-20 12:21:34.820 Client[216:18919] THREAD WARNING: ['PushNotification'] took '49.457031' ms. Plugin should use a background thread.
2015-01-20 12:21:34.868 Client[216:19340] Sending request: {"request":{"sounds":[],"timezone":"0","device_type":1,"os_version":"8.1.1","push_token":"redacted","application":"redacted","language":"en","gateway":"sandbox","hwid":"redacted","package":"redacted","device_model":"iPod5,1","jailbroken":0,"app_version":"0.0.1","v":"2.4"}}
2015-01-20 12:21:34.871 Client[216:19340] To urL https://cp.pushwoosh.com/json/1.3/registerDevice
2015-01-20 12:21:35.625 Client[216:19340] Response "200 no error": string: {"status_code":200,"status_message":"OK","response":{"iosCategories":[]}}
2015-01-20 12:21:35.644 Client[216:19340] Registered for push notifications: redacted
```

Can you provide any thoughts/feedback on this issue?

Thanks

**Comment by robdick** [comment]
+1

**Comment by mikeyrtw** [comment]
Hi, this is a problem I'm having also, especially as when used in an AngularJS app it causes my promise to resolve before the user has made a choice.

**Comment by robdick** [comment]
+1 (me again too please - my last + got negated)

**Comment by sean-hill** [comment]
+1 Exact same issue. @shaders any help here?

**Comment by sweinertjr** [comment]
+1 Also having this.

**Comment by sean-hill** [comment]
I'm no Objective C guru, but it looks like they send a `nil` callback immediately when `registerDevice` is called, then registers. Hence why we immediately get the error callback fired.

	- (void)registerDevice:(CDVInvokedUrlCommand*)command {
		[self.callbackIds setValue:command.callbackId forKey:@"registerDevice"];
		CDVPluginResult* pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_NO_RESULT messageAsDictionary:nil];
		[pluginResult setKeepCallbackAsBool:YES];
		[self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
		
		[[PushNotificationManager pushManager] registerForPushNotifications];
	}

**Comment by shaders** [comment]
Checking this now. What Cordova version do you use?
Maybe they changed something because the plugin returns "CDVCommandStatus_NO_RESULT" which should not trigger callback.

**Comment by sean-hill** [comment]
cordova -v
    4.1.2

**Comment by shaders** [comment]
Could you tell me the result of this command as well?
cordova platforms list

**Comment by sean-hill** [comment]
$ cordova platforms list
    Installed platforms: android 4.0.0-dev, ios 3.7.0
    Available platforms: amazon-fireos, blackberry10, browser, firefoxos

**Comment by shaders** [comment]
Awesome, thanks!

**Comment by shaders** [comment]
Indeed this is a bug of Cordova 4.1 and 4.2
https://issues.apache.org/jira/browse/CB-8063

I'm going to remove CDVCommandStatus_NO_RESULT as a workaround and will push an update (version 3.4.7).

**Comment by shaders** [comment]
done

**Comment by cgwyllie** [comment]
@shaders That's great, thanks!

**Comment by Wang0620** [comment]
I am getting same issue: 
- location services authorization status has not been determined yet
I am using cordova 5.1.1 and pushwoosh latest version. Please let me know how can I fix this problem. 
Thanks a lot for your help.

**Comment by shaders** [comment]
This is an error about location services not authorized yet.
1. It's ok if you don't use location services
2. The user simply didn't press "Allow to use location" when using location services
3. You forgot to add "NSLocationWhenInUseUsageDescription" or "NSLocationAlwaysUsageDescription" to your Info.plist file (however you should see explicit error about that in the console)
