### ISSUE TITLE
Callback firing too early on iOS

### ISSUE THREAD

**Issue by sandstrom** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#76]
I'm integrating your plugin and it has worked pretty well so far. A few issues though.

I've noticed that `registerDevice` fires the fail callback immediately on iOS (followed by the true callback later). First, it would be great if you documented this behaviour, because it's bound to trip people up.

Also, do you have any remedy planned?

The Cordova-people has responded to your ticket:
https://issues.apache.org/jira/browse/CB-8063

The line in question:
https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/blob/4a36bbb0488bf7d68ad21b8248e47e43ab3cd049/src/ios/PushNotification.m#L95

**Comment by shaders** [comment]
Is this still happening? Which version do you use?
It used to be bug with cordova which was workarounded.

**Comment by sandstrom** [comment]
Latest version

**Comment by shaders** [comment]
I cannot reproduce this. Are you sure you have lines 98-101 commented out?

**Comment by sandstrom** [comment]
Yes (I haven't touched the native code, I'm using the plugin as-is).

Below is our workaround, perhaps that's helpful:

    var promise = new Promise(function(resolve, reject){
      window.plugins.pushNotification.registerDevice(function(res){
        info('Device registered for push notifications');
        debug(res.deviceToken);
        resolve(true);
      }, function(res){
        // An issue with Cordova/iOS cause this callback to fire immediately (success will be called later if it was
        // successful). When this happens res will be `null`. We catch this special case and do nothing, since the true
        // callback firing will occure at a later point in time.
        // https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/issues/76
        // https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/blob/4a36bbb0488bf/src/ios/PushNotification.m#L95
        // https://issues.apache.org/jira/browse/CB-8063
        if (platform == 'ios' && !res) { // special case
          debug('Early callback triggered by cordova, ignoring');
        } else { // normal case
          warn('Device could not be registered for push notifications');
          debug(res.error);
          resolve(false);
        }
      };
    });

**Comment by shaders** [comment]
I see you are using version 3.4.6? This has been workarounded in 3.4.7. Could you please update the plugin?

**Comment by shaders** [comment]
this was fixed.
