### ISSUE TITLE
registerDevice() fires no callback

### ISSUE THREAD

**Issue by danielefenix** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#77]
Thank you very much for the Pushwoosh plugin. 
I am experiencing some problems unfortunately.

Info:
I am building an application with PhoneGap Build so the installation of the plugin is automatic.
I am currently using the latest version (no version is specified in config.xml) of the Pushwoosh plugin and v3.6.3 of Phonegap.
The push notifications are working but I suspect this is not because of your code: I previously installed a version of the app that registered my device to PushWoosh and i think i have never be unregistered.
I am not using Sencha but Plain Javascript for the moment.
The listening of ‘deviceReady’ event is working properly because GoogleAnalytics plugin is initialised too in that moment and it is working properly.
The ‘platform switch’ controller works properly (let’s focus on iOS).
pw_appid is correctly set with the Pushwooh app code.
I checked with an alert(typeof pushNotification.registerDevice) right before to be invoked and it prints correctly ‘function’.

The problem is that pushNotification.registerDevice fires no callback for success, no callback for error. (Checked with an alert on it)
Once the app is opened, the listener of ‘push-notification’ does not work.

Aside of this, I would ask you a suggestion too: how would you test a plugin installation? I mean, what are the tools you use to check if a plugin is working. Currently my workflow is quite slow, because any time i make some modification to my code i have to compress, build and upload the app on PhoneGap Build. Do you know some configuration to test it on Desktop? would you suggest some environment configuration taking in account I installed Phonegap CLI, some emulator on which i installed the Phonegap Client but it seems i don’t see the plugins, even if in this case I installed them via CLI.

Best Regards.

Daniele

**Comment by shaders** [comment]
Have you checked your mobileprovisioning profile so it does have "aps-environment" entry and push compatible? What do you see in the devices console log?

**Comment by danielefenix** [comment]
Thank you @shaders for your reply.
I found out that there was something on my own device (an iPhone 5) given that i could register other iOS device. I performed a factory reset and the issue is now solved.

Thank you for your support in any case.
Best regards.
