### ISSUE TITLE
remote-notification log

### ISSUE THREAD

**Issue by sean-hill** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#78]
Hey, this might not be an issue, but I'm just putting it out there in case it is. When I launch of my application, I get this error.

`You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.`

The only notifications I'm using in my app is Pushwoosh, so I was thinking this log was via Pushwoosh code. Just FYI! :)

**Comment by shaders** [comment]
Hi,

This warning is safe.

This function is used by "newsstand push". However to use this functionality you have to put correct background mode in Info.plist. If you don't - the functionality would not be available, but everything will work as expected.
