### ISSUE TITLE
Make `READ_PHONE_STATE` permission optional

### ISSUE THREAD

**Issue by sandstrom** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#79]
A plugin configuration that skips/removes the `READ_PHONE_STATE` used on the Android platform. The trouble with asking for many, non-needed, permissions is that Play Store conversion rates suffer heavily. Limiting permissions increases downloads.

Since Cordova plugins abstract away the underlying platforms, surfacing a `config.xml` level setting to skip this permission is desired:

Earlier discussion:
https://github.com/Pushwoosh/pushwoosh-android-sdk/issues/9

**Comment by shaders** [comment]
Could you specify what do you mean by config.xml level?

**Comment by sandstrom** [comment]
A preference tag `<preference name="PWEnablePhoneStatePermission" value="false" />` that would disable inclusion/request of the read phone state permission.

The commit to this plugin does something similar:
https://github.com/pelish8/cordova-plugin-statusbar/commit/a83cf8b17c0e0f89496eaeadcbaaf8853cc2e9c6?w=1

I hope this helps. I haven't actually authored any plugin myself, so I had to search around a bit and this is what I found.

**Comment by shaders** [comment]
It is possible to get preferences value from the code, however during AndroidManifest.xml creation there are no options available. The choice is either dropping permission completely from the plugin or leaving it there.

**Comment by sandstrom** [comment]
I appreciate your investigation into this!

I think it should be possible via a plugin-hook. Perhaps you could inquiry with some of the core contributors via email: https://github.com/apache/cordova-android/graphs/contributors

**Comment by shaders** [comment]
The problem is that the AndroidManifest.xml is modified by plugman during the plugin install. As a contributor to plugman I know how it works :) 

Actually I think dropping this permission is a good idea.

**Comment by sandstrom** [comment]
Ah, okay, I haven't so I wouldn't know :)

I definitely approve of dropping it altogether!

**Comment by boynet** [comment]
+1 for dropping this

**Comment by shaders** [comment]
Dropped in 3.4.11Dropped in 3.4.11
