### ISSUE TITLE
Disable InApp Tracking on iOS

### ISSUE THREAD

**Issue by RonnySchleicher** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#80]
In the current plugin version (for iOS) when the app starts, all InApp Purchases (InApp tracking) are sent to the Pushwoosh server. Is it possible to add something here to disable this function or trigger manually.

##### Maybe like this in the ***config.xml***:
```XML
<feature name = "PushNotification">
        <param name = "ios-package" value = "PushNotification" />
        <preference name = "enableInAppTracking" value = "false" />
</feature>
```

**Comment by shaders** [comment]
You can set "Pushwoosh_NO_TRACK_IAP" to "YES" in Info.plist.  The plugin version will be 3.4.13

See: http://phonegap.com/blog/2014/01/30/customizing-your-android-manifest-and-ios-property-list-on-phonegap-build/

**Comment by RonnySchleicher** [comment]
The new version works fine. Thanks for the help.
