### ISSUE TITLE
iOS issue

### ISSUE THREAD

**Issue by mtamony** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#81]
Something seems to be wrong with Cordova and Pushwoosh again.

    2015-02-13 14:43:06.862 SBCERAApp[433:312254] You've implemented -[<UIApplicationDelegate>
    application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add
    "remote-    notification" to the list of your supported UIBackgroundModes in your Info.plist.

Here is where it seems to be failing:

    onDeviceReady: function() {
    
    app.receivedEvent('deviceready');

    initPushwoosh();
    
    },

If I put an alert before app.receivedEvent it fires, if I put it after it does not fire.

Sorry if I'm not presenting the correct info. I realize it seems like deviceready is not firing but I use device ready successfully elsewhere.

Thanks

**Comment by shaders** [comment]
This warning is harmless. It means your app cannot receive silent pushes. That's fine and regular pushes are not affected.

However it is up to you to make your Javascript code to be correct. We have a sample project for a jump start:  
https://github.com/Pushwoosh/phonegap-3-sample-app

**Comment by mtamony** [comment]
I appreciate you pointing me to a sample app but how about adding the link
to where the directions on the website are located. There is a significant
difference with what the website provides and this sample app code.

**Comment by shaders** [comment]
What would be the difference?

**Comment by mtamony** [comment]
The code from the website was not working. I'm not sure why specifically.
The code from this sample seems to be working at least for registration
though I don't seem to be receiving pushes. It could be that my coding is
not good enough to quickly find the problems. Here is what I perceive to be
a challenge for companies like yours though. Applications like Phonegap
have made creating mobile applications somewhat easy for non-coding folks
like me. Unfortunately when things break we come to tech gurus like you to
find a fix. Having consistent, easy to understand code across website
guides, GitHub, etc is important. This is just my opinion though. Pushwoosh
has always been super helpful in solving problems.

**Comment by shaders** [comment]
Thank you. Please note this is not support forum. You can contact Pushwoosh support team by using contact form on Pushwoosh website. This place is for SDK discussion, methods, functions, code, etc.
