### ISSUE TITLE
nullpointerexception when running plugin on Android with MobileChromeApps

### ISSUE THREAD

**Issue by laustdeleuran** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#83]
I'm trying to run a Apache Cordova based app with the PushWoosh plugin on Android. To avoid fragmentation problems on Android, we're using [MobileChromeApps](https://github.com/MobileChromeApps/mobile-chrome-apps) to build our Android version of the app. However, I can't register the device for push messages via PushWoosh. The code is working flawlessly on iOS.

The error happens as soon as I run `plugins.pushNotification.registerDevice`.

This is what `adb logcat` gives me:

	D/PushNotifications(17915): Plugin Called
	W/System.err(17915): java.lang.NullPointerException
	W/System.err(17915): 	at com.pushwoosh.plugin.pushnotifications.PushNotifications.internalRegister(PushNotifications.java:189)
	W/System.err(17915): 	at com.pushwoosh.plugin.pushnotifications.PushNotifications.execute(PushNotifications.java:390)
	W/System.err(17915): 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:82)
	W/System.err(17915): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:128)
	W/System.err(17915): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:63)
	W/System.err(17915): 	at org.apache.cordova.engine.crosswalk.XWalkExposedJsApi.exec(XWalkExposedJsApi.java:40)
	W/System.err(17915): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
	W/System.err(17915): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:28)
	W/System.err(17915): 	at android.os.Handler.dispatchMessage(Handler.java:99)
	W/System.err(17915): 	at android.os.Looper.loop(Looper.java:137)
	W/System.err(17915): 	at android.os.HandlerThread.run(HandlerThread.java:60)

It looks like the Java code fails somehow - but why and how, I don't know (web developer by heart, I don't know Java). The app never calls any remote resources, so the error must be somewhere in the app setup.

Any ideas? All help is appreciated (and might even be rewarded with a beer if you're in Copenhagen).

Thank you so much!

[Stackoverflow question here](http://stackoverflow.com/questions/28769019/pushwoosh-on-android-nullpointerexception-when-running-registerdevice).

**Comment by laustdeleuran** [comment]
A more detailed look at `adb logcat -s System.err` reveals that the initialization fails, probably resulting in the other errors as well:

	W/System.err( 7439): org.json.JSONException: No value for projectid
	W/System.err( 7439): 	at org.json.JSONObject.get(JSONObject.java:354)
	W/System.err( 7439): 	at org.json.JSONObject.getString(JSONObject.java:510)
	W/System.err( 7439): 	at com.pushwoosh.plugin.pushnotifications.PushNotifications.initialize(PushNotifications.java:174)
	W/System.err( 7439): 	at com.pushwoosh.plugin.pushnotifications.PushNotifications.execute(PushNotifications.java:384)
	W/System.err( 7439): 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:82)
	W/System.err( 7439): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:128)
	W/System.err( 7439): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:63)
	W/System.err( 7439): 	at org.apache.cordova.engine.crosswalk.XWalkExposedJsApi.exec(XWalkExposedJsApi.java:40)
	W/System.err( 7439): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
	W/System.err( 7439): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:28)
	W/System.err( 7439): 	at android.os.Handler.dispatchMessage(Handler.java:99)
	W/System.err( 7439): 	at android.os.Looper.loop(Looper.java:137)
	W/System.err( 7439): 	at android.os.HandlerThread.run(HandlerThread.java:60)
	W/System.err( 7439): java.lang.NullPointerException
	W/System.err( 7439): 	at com.pushwoosh.plugin.pushnotifications.PushNotifications.internalRegister(PushNotifications.java:190)
	W/System.err( 7439): 	at com.pushwoosh.plugin.pushnotifications.PushNotifications.execute(PushNotifications.java:393)
	W/System.err( 7439): 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:82)
	W/System.err( 7439): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:128)
	W/System.err( 7439): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:63)
	W/System.err( 7439): 	at org.apache.cordova.engine.crosswalk.XWalkExposedJsApi.exec(XWalkExposedJsApi.java:40)
	W/System.err( 7439): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
	W/System.err( 7439): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:28)
	W/System.err( 7439): 	at android.os.Handler.dispatchMessage(Handler.java:99)
	W/System.err( 7439): 	at android.os.Looper.loop(Looper.java:137)
	W/System.err( 7439): 	at android.os.HandlerThread.run(HandlerThread.java:60)
	W/System.err( 7439): java.lang.NullPointerException
	W/System.err( 7439): 	at com.pushwoosh.plugin.pushnotifications.PushNotifications.internalRegister(PushNotifications.java:190)
	W/System.err( 7439): 	at com.pushwoosh.plugin.pushnotifications.PushNotifications.execute(PushNotifications.java:393)
	W/System.err( 7439): 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:82)
	W/System.err( 7439): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:128)
	W/System.err( 7439): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:63)
	W/System.err( 7439): 	at org.apache.cordova.engine.crosswalk.XWalkExposedJsApi.exec(XWalkExposedJsApi.java:40)
	W/System.err( 7439): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
	W/System.err( 7439): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:28)
	W/System.err( 7439): 	at android.os.Handler.dispatchMessage(Handler.java:99)
	W/System.err( 7439): 	at android.os.Looper.loop(Looper.java:137)
	W/System.err( 7439): 	at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by laustdeleuran** [comment]
So, it might all be because I had no idea that I had to configure a Google Project Number with the GCM API enabled. Trying it now, and will report back.

**Comment by laustdeleuran** [comment]
Yes, with the Project Number, I can now register the device, and the full API seems to be working. Only one major caveat: I'm not receiving any push notifications at all on my test device. the `'push-notification'` event is never fired. Still debugging...

**Comment by shaders** [comment]
The easiest way is to try sample project (https://github.com/Pushwoosh/phonegap-3-sample-app/). Make sure you get GCM credentials correctly and then check if you can see subscriber number increased in the Pushwoosh control panel. Then send a push and check its status from the "push status" page.

**Comment by Pmagz** [comment]
Hi Shaders,

Kindly assist, i cannot register a device as the error is 

04-19 07:15:08.179: D/CordovaLog(2454): ["failed to register ",null]

My initPushwoosh function is as follows:

function initPushwoosh()
{
    var pushNotification = window.plugins.pushNotification;
 
    pushNotification.registerDevice({ projectid: "mygoogleprojectid", appid : "pushwooshappid" },
        function(status) {
            var pushToken = status;
            console.warn('push token: ' + pushToken);
        },
        function(status) {
            console.warn(JSON.stringify(['failed to register ', status]));
        }
    );
 
    document.addEventListener('push-notification', function(event) {
        var title = event.notification.title;
            var userData = event.notification.userdata;
 
            if(typeof(userData) != "undefined") {
            console.warn('user data: ' + JSON.stringify(userData));
        }
 
        navigator.notification.alert(title);
    });
}

Could there be something im missing or need to be added? Also when i change to:

function initPushwoosh()
{
    var pushNotification = window.plugins.pushNotification;
 
    //set push notifications handler
    document.addEventListener('push-notification', function(event) {
        var title = event.notification.title;
        var userData = event.notification.userdata;
                                 
        if(typeof(userData) != "undefined") {
            console.warn('user data: ' + JSON.stringify(userData));
        }
                                     
        alert(title);
    });
 
    //initialize Pushwoosh with projectid: "GOOGLE_PROJECT_NUMBER", pw_appid : "PUSHWOOSH_APP_ID". This will trigger all pending push notifications on start.
    pushNotification.onDeviceReady({ projectid: "GOOGLE_PROJECT_NUMBER", pw_appid : "PUSHWOOSH_APP_ID" });
 
    //register for pushes
    pushNotification.registerDevice(
        function(status) {
            var pushToken = status;
            console.warn('push token: ' + pushToken);
        },
        function(status) {
            console.warn(JSON.stringify(['failed to register ', status]));
        }
    );
}

I get:

04-19 07:58:49.535: W/System.err(3105): org.json.JSONException: Index 0 out of range [0..0)
04-19 07:58:49.551: W/System.err(3105): 	at org.json.JSONArray.get(JSONArray.java:263)
04-19 07:58:49.551: W/System.err(3105): 	at org.json.JSONArray.getJSONObject(JSONArray.java:480)
04-19 07:58:49.555: W/System.err(3105): 	at com.pushwoosh.plugin.pushnotifications.PushNotifications.initialize(PushNotifications.java:153)
04-19 07:58:49.575: W/System.err(3105): 	at com.pushwoosh.plugin.pushnotifications.PushNotifications.execute(PushNotifications.java:364)
04-19 07:58:49.575: W/System.err(3105): 	at org.apache.cordova.api.CordovaPlugin.execute(CordovaPlugin.java:66)
04-19 07:58:49.579: W/System.err(3105): 	at org.apache.cordova.api.PluginManager.exec(PluginManager.java:224)
04-19 07:58:49.579: W/System.err(3105): 	at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:51)
04-19 07:58:49.583: W/System.err(3105): 	at android.webkit.JWebCoreJavaBridge.sharedTimerFired(Native Method)

Then java.lang.NullPointerException follows after this. Kindly assist. I have been having this problem for the last three weeks :(.

Kind Regards,
Peter

**Comment by shaders** [comment]
closed for inactivity
