### ISSUE TITLE
.registerDevice() returns failed: undefined on Blackberry10

### ISSUE THREAD

**Issue by laustdeleuran** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#84]
When running `.registerDevice()` on my BB10 test device, the function runs the error callback, but with no arguments:

http://cl.ly/image/2I3Y2u06101u

I'm using [the iPhone syntax/version of the plugin](https://www.pushwoosh.com/programming-push-notification/ios/ios-additional-platforms/push-notification-sdk-integration-for-phonegap/), not [the WebWorks version](https://www.pushwoosh.com/programming-push-notification/blackberry/blackberry-5-7/blackberry-html5-webworks-push-notification-sdk/), as that article seems to be referencing an old version of the API.

My application is developed purely using Cordova and the PW plugin. I'm still waiting for my code signing identity from Blackberry to allow for pushes, but right now the silent fail is pretty worrying to me.

What is going on?

Thanks.

**Comment by laustdeleuran** [comment]
Rereading the documentation leads me to suspect that the plugin doesn't even support Blackberry10. Is there any way to remedy this?

**Comment by laustdeleuran** [comment]
This older repository holds BB10 support - can I just port the [pushwoosh.js from the BB10 folder](https://github.com/Pushwoosh/phonegap-cordova-push-notifications/blob/master/BlackBerry/Blackberry10-HTML/pushwoosh.js) from there?

**Comment by shaders** [comment]
No, you doing it wrong. :)

Yes, Pushwoosh PGB plugin does not include Blackberry support. The reason for this is that there is no extra code/plugin needed, everything is done via JS.

Do NOT use iOS plugin for BB10 it will never ever work no matter how hard you try.

This is what you need for BB10:  
https://www.pushwoosh.com/programming-push-notification/blackberry/blackberry-10/blackberry-10-webworks-2-0/

There is a sample as well:  
https://github.com/Pushwoosh/pushwoosh-sdk-samples/tree/master/Native/Blackberry-10-HTML5-Webworks

Please note that Webworks is based on Phonegap/Cordova, will be compatible and will have the same project layout.
