### ISSUE TITLE
onDeviceReady() with timezone for ios/android

### ISSUE THREAD

**Issue by Pranay92** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#86]
Hi,

We're trying to register our device with the timezone offset but since the plugin only accepts success and error callback functions, I think we can only specify `timezone` on `onDeviceReady()` ? However I can't find any resource as to how to pass in and what variable name is needed for timezone offset. (both for Android and iOS)

Is there any way I can pass in the `timezone` on either registring/onDeviceReady() functions?

Thanks.

**Comment by shaders** [comment]
You don't need to pass timezone, SDK detects timezone from device settings automatically.
