### ISSUE TITLE
Android builds failing

### ISSUE THREAD

**Issue by neil-rowe** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#89]
After adding the pushwoosh plugin to my app, It no longer builds for android. through phonegap build. 
Phonegap personell have narrowed the issue down to the pushwoosh plugin as noted here:

http://community.phonegap.com/nitobi/topics/failed-android-builds?utm_source=notification&utm_medium=email&utm_campaign=new_reply&utm_content=reply_button&reply[id]=15597402#reply_15597402

Here is what is happening:

I am getting the following error when trying to build the android apk. The iOS build goes through perfectly every time. my plugins are as follows and are all android compatible aside from status bar which should not load for android. It would be great if the build issues could be resolved.

Plugin	Source	Version	Latest	Platforms 
com.phonegap.plugin.statusbar pgb	1.1.0	1.1.0	ios 
com.phonegap.plugins.pushplugin pgb	2.4.0	2.4.0	android,ios,winphone 
com.pushwoosh.plugins.pushwoosh pgb	3.4.2	3.4.2	android,ios,winphone 
de.appplant.cordova.plugin.local-notification pgb	0.8.1	0.8.1	android,ios 
nl.x-services.plugins.toast pgb	2.0.2	2.0.2	android,ios,winphone 
org.apache.cordova.device pgb	0.2.12	0.2.12	android,ios,winphone 
org.apache.cordova.dialogs pgb	0.2.10	0.2.10	android,ios,winphone 
org.apache.cordova.network-information pgb	0.2.12	0.2.12	android,ios,winphone 
org.apache.cordova.splashscreen pgb	0.3.4	0.3.4	android,ios,winphone 
org.apache.cordova.vibration pgb	0.3.11	0.3.11	android,ios,winphone 

error: 

"Oh geez. Your build failed. Sorry, but a problem occurred on the build server 
notify us" 

the log is as follows for compile and listed errors: 

-compile: 
[javac] Compiling 86 source files to /project/bin/classes 
[javac] /project/src/com/plugin/gcm/CordovaGCMBroadcastReceiver.java:14: error: method does not override or implement a method from a supertype 
[javac] @Override 
[javac] ^ 
[javac] /project/src/com/plugin/gcm/GCMIntentService.java:24: error: constructor GCMBaseIntentService in class GCMBaseIntentService cannot be applied to given types; 
[javac] super("GCMIntentService"); 
[javac] ^ 
[javac] required: no arguments 
[javac] found: String 
[javac] reason: actual and formal argument lists differ in length 
[javac] Note: Some input files use or override a deprecated API. 
[javac] Note: Recompile with -Xlint:deprecation for details. 
[javac] Note: /project/src/com/arellomobile/android/push/request/RequestManager.java uses unchecked or unsafe operations. 
[javac] Note: Recompile with -Xlint:unchecked for details. 
[javac] 2 errors 

BUILD FAILED 
/home/ec2-user/android-sdk/tools/ant/build.xml:720: The following error occurred while executing this line: 
/home/ec2-user/android-sdk/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

**Comment by neil-rowe** [comment]
..OK problem solved. I had the pushplugin also loading still from an earlier version which was causing issues. got rid of it in config and all is well :)

**Comment by shaders** [comment]
Great! Closing issue.
