### ISSUE TITLE
not getting event "push-notification" in latest 3.5.0 iOS build

### ISSUE THREAD

**Issue by tysjiang** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#90]
In the latest 3.5.0 and 3.4.16 versions of pushwoosh, the event "push-notification" does not get triggered when a push comes through while inside the app, the push would show as an alert banner with a cordova icon on top

I've simplified the listener to just this to make sure it's not my code:
                document.addEventListener('push-notification', function(event) {
                                alert('got it');
                            }); 

Yet, it still doesn't get triggered.
All the other stuff works as usual, registering devices, setting badge counts, etc.
I'm building with Intel XDK v1912 Cordova (4.1.2) iOS, tested on a iPhone 6, iPhone 5s, iPad with iOS 8.3

Also to note, with the exact same config and code, everything works if I switch to pushwoosh 3.4.0
(and if I remember correctly, it worked up to a later version 3.4.x also, just not 16 and not 3.5.0)

**Comment by shaders** [comment]
Hi,

Fixed in 3.5.1

Thanks!
