### ISSUE TITLE
White notifications in Android 5 Lollipop

### ISSUE THREAD

**Issue by tapionx** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#93]
On android lollipop i get a white icon on the push notifications.
I want to specify a different icon to use for the notifications so i can set the alpha channel as i want.
I tried to follow the instructions in the FAQ https://www.pushwoosh.com/programming-push-notification/android/android-faq/#lollipop-icon
but i don't understand where to put the file pw_notification.png

**Comment by shaders** [comment]
Hi,

Put it in "res/drawable" folder

**Comment by matthewbecker1990** [comment]
Just adding to this issue -
Would really appreciate a way to set the Accent Color behind notifications in the notifications tray for API 21+

**Comment by jQrgen** [comment]
+1

**Comment by shaders** [comment]
It's called "Image Background Color" in the control panel (should be really renamed).

**Comment by MaicolBen** [comment]
I tried adding pw_notification.png file to the res/drawable and it didn't worked for me, could it be difficult to implement  the same fix that [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push) did in https://github.com/phonegap/phonegap-plugin-push/issues/20?

**Comment by MaicolBen** [comment]
I tried adding pw_notification.png file to the res/drawable and it didn't worked for me, could it be difficult to implement  the same fix that [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push) did in https://github.com/phonegap/phonegap-plugin-push/issues/20?

**Comment by MaicolBen** [comment]
I tried adding pw_notification.png file to the res/drawable and it didn't worked for me, could it be difficult to implement  the same fix that [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push) did in https://github.com/phonegap/phonegap-plugin-push/issues/20?

**Comment by shaders** [comment]
Are you sure you put it in the res/drawable folder? The one in the the platfroms/android folder?

**Comment by MaicolBen** [comment]
@shaders Yes. I had to downgrade the sdk to get it work instead.

**Comment by CookieCookson** [comment]
@MaicolBen: Did you ever get this working with the latest SDK?

**Comment by acti0nm4n** [comment]
I got this working by ensuring all the icon types (xxhdpi, mdpi etc) had the small notification icon I required, then set the android_icon parameter to it (minus suffix) in the PW API request.
