### ISSUE TITLE
registerDevice() token is null

### ISSUE THREAD

**Issue by dsbahr** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#97]
Hi. 

We are using Pushwoosh phonegap build plugin for handling notifications. However when I'm trying to call registerDevice() the 'token' value in handleSuccess is null.

I can't see any errors or anything? (This code has worked previously). 

Any ideas on what I'm doing wrong and could be causing the issue?

This happens on iOS8, Android 4.4.4 and 4.4.2, however on Android 5 and 5.1 the 'token' value  has a value, and is: 

'Attempt to invoke virtual method 'void com.arellomobile.android.push.PushManager.registerForPushNotifications()' on a null object reference'.

So I guess Android 5+ is not supported?

The code looks like this: 

	pn.registerDevice({
					alert: true,
					badge: true,
					sound: true,
					projectid: host.buildSettings.googleApiProjectNumber,
					pw_appid: host.buildSettings.pushwooshAppCode,
					appid: host.buildSettings.pushwooshAppCode,
					appname: 'MyAppName'
				}, function handleSuccess(token) {
					console.log('deviceRegistration.handleSuccess', token);
					var deviceToken = token.deviceToken || token;
					var data = {
						success: true,
						token: deviceToken
					};
					storage(data);
					// console.log('notifications.register.success', deviceToken);
					deferred.resolve(data);
				}, function handleError(status) {
					console.log('deviceRegistration.handleError', status);
					saved = {
						status: status,
						success: false
					};
					storage(saved);
					// console.log('notifications.register.failed', status);
					deferred.resolve(saved);
				});

Thanks, 

/David

**Comment by shaders** [comment]
That's an old integration code. Please check the integration guide. registerDevice now has different parameters and first parameters were moved to onDeviceReady function.

**Comment by dsbahr** [comment]
Thank you for a quick answer, just found out at the same :)
