### ISSUE TITLE
API improvement, need direct check for notification on launch

### ISSUE THREAD

**Issue by zarko-tg** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#98]
We have an issue with the current plugin API regarding app launch and push notifications.
Basically we want a different push notification to send the user to a different view in the app.
There is a default view and some other views.
A normal hard launch of the app through its app icon needs to show the default view, while an app launch by tapping on the notification needs to send the user directly to one of few views depending on the user data in the push notification.

This is a timing problem because we don't know when/if the "push-notification" will trigger. The fact that PushNotification.prototype.onDeviceReady triggers the 'push-notification' event when there is a pending notification and not in the opposite case is unfortunate for the scenario in question.

Can you improve the API regarding this challenge? Have a look at UrbanAirship's getLaunchNotification (http://docs.urbanairship.com/platform/phonegap.html#getLaunchNotification) for inspiration.

By then we'll probably go for polling at small intervals, something that will cause a small delay at launch and it's a hack that I'd rather not proceed with.

Thanks and hope to hear back soon.

**Comment by shaders** [comment]
Hi,

That should be easy to implement. I'll keep you posted.

**Comment by shaders** [comment]
Done, check 3.5.4 version of the plugin.
Also here:
https://rawgit.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/master/Documentation/files/PushNotification-js.html#PushNotification.getLaunchNotification

Currently available for iOS and Android, WP coming soon.

**Comment by zarko-tg** [comment]
I'm on it! Many thanks
